name: Release
on:
  push:
    tags:
      - '*'

jobs:
  - name: Tag
    id: tag
    uses: dawidd6/action-get-tag@v1
    with:
      strip_v: false
  - name: Release
    run: echo ${{ steps.tag.outputs.tag }}
