name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    name: Sphinx documentation to GitHub pages
    steps:
      - uses: actions/checkout@v4
      - name: Building HTML
        uses: astral-sh/setup-uv@v5
      - shell: bash -l {0}
        run: |
          uv run sphinx-build -M html docs/source/ docs/build/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
